#!/bin/bash

echo "============================================================"
echo "oh-my-openagent (原 oh-my-opencode) 安装脚本"
echo "============================================================"
echo ""
echo "由于网络问题，请手动执行以下步骤安装插件："
echo ""
echo "方法1: 使用 Git 克隆 (推荐)"
echo "------------------------------------------------------------"
echo "git clone https://github.com/code-yeongyu/oh-my-openagent.git \\"
echo "    ~/.oh-my-zsh/custom/plugins/oh-my-openagent"
echo ""
echo "方法2: 手动下载"
echo "------------------------------------------------------------"
echo "1. 访问: https://github.com/code-yeongyu/oh-my-openagent"
echo "2. 点击 'Code' -> 'Download ZIP'"
echo "3. 解压后将文件夹重命名为 'oh-my-openagent'"
echo "4. 移动到: ~/.oh-my-zsh/custom/plugins/"
echo ""
echo "方法3: 使用 Gitee 镜像"
echo "------------------------------------------------------------"
echo "如果 GitHub 访问慢，可以配置 Gitee 镜像后重试"
echo ""
echo "============================================================"
echo "安装完成后配置步骤："
echo "============================================================"
echo ""
echo "1. 编辑 ~/.zshrc 文件："
echo "   vim ~/.zshrc"
echo ""
echo "2. 在 plugins 中添加 oh-my-openagent："
echo "   plugins=(git oh-my-openagent)"
echo ""
echo "3. 保存后重新加载配置："
echo "   source ~/.zshrc"
echo ""
echo "============================================================"
echo "当前状态："
echo "============================================================"
echo ""
echo "✅ oh-my-zsh: 已安装"
echo "✅ .zshrc: 已创建"
echo "❓ oh-my-openagent: 待手动安装"
echo ""
echo "============================================================"